### ISSUE TITLE
Problems running the test files.

### ISSUE THREAD

**Issue by Kaasstengel** [elupus/nibeuplink#2]
I don't know if anyone is still working on this git, but I'm trying to get everything to work on my pc and having some issues.

I have installed the package and I can run `nibeuplink` in the terminal. However, don't have a NIBE product assigned to my account yet. That is why I was trying to work out how the tests and fake uplink work. 

I tried running `$ pytest test_basic.py` but I get the following error: ` fixture 'event_loop' not found
` Any suggestions on dealing with this, or am I trying the wrong thing entirely?

**Comment by elupus** [comment]
You need some additional requirements. Check setup.py for the extra requirements.

**Comment by elupus** [comment]
Best is to install it editible in a virtual env. I think it needs to be installed for tests to work.

pip install -e . [tests]

**Comment by Kaasstengel** [comment]
I have done all that but still get  `fixture 'event_loop' not found
`

**Comment by elupus** [comment]
What version of python? Travis build that tests this is at least running 3.6.

And you are running in a virtualenv right?

**Comment by Kaasstengel** [comment]
I'm using python 3.6.5
and yes I am running in an env, I am using anaconda3 and pycharm.

**Comment by elupus** [comment]
I'm unsure what the issue could be. It did run fine on Hudson and on my computer's a few months ago.
